/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewIndexRouteImport } from './routes/preview/index'
import { Route as PreviewComponentRouteImport } from './routes/preview/$component'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: '/preview/',
  path: '/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewComponentRoute = PreviewComponentRouteImport.update({
  id: '/preview/$component',
  path: '/preview/$component',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview/$component': typeof PreviewComponentRoute
  '/preview': typeof PreviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview/$component': typeof PreviewComponentRoute
  '/preview': typeof PreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview/$component': typeof PreviewComponentRoute
  '/preview/': typeof PreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preview/$component' | '/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preview/$component' | '/preview'
  id: '__root__' | '/' | '/preview/$component' | '/preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewComponentRoute: typeof PreviewComponentRoute
  PreviewIndexRoute: typeof PreviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/': {
      id: '/preview/'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$component': {
      id: '/preview/$component'
      path: '/preview/$component'
      fullPath: '/preview/$component'
      preLoaderRoute: typeof PreviewComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewComponentRoute: PreviewComponentRoute,
  PreviewIndexRoute: PreviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
